### ISSUE TITLE
Tracking Feature Requests on GitHub

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2114]
We should get rid of [the feature Request page](http://visjs.org/featureRequests.html) and track feature requests as issues on github. The manual effort to synchronize is just too great!

* [x] Reopen all issues listed on the [featureRequests page](http://visjs.org/featureRequests.html) and label as "enhancement"
* [x] Check the status of these issues, rename the title to something understandable.
* [x] Remove the "featureRequests.html". Better: Remove all links to this file and change the file to auto-redirect to [issues labeld as enhancement](https://github.com/almende/vis/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement).

**Comment by mojoaxel** [comment]
@ludost Is it ok with you/almende if we get rid of the feature-request page again and manage them here on github?

**Comment by ludost** [comment]
Yes, no problem. Do what works best for you guys.

**Comment by mojoaxel** [comment]
closed with baf8d59a3018a53f0c2d57b0dc4465108354b1a8
